#!/usr/bin/env bash

# Script to generate test FASTQ files for ExpressDiff pipeline testing

set -e

echo "🧬 Creating test FASTQ files for ExpressDiff..."

# Create test data directory
mkdir -p test_data

# Generate simple test FASTQ files (paired-end, 3 samples)
samples=("sample_A" "sample_B" "sample_C")

for sample in "${samples[@]}"; do
    echo "Creating ${sample}..."
    
    # Forward reads (_1)
    cat > "test_data/${sample}_1.fq" << 'EOF'
@SEQ_1_forward
ATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCG
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@SEQ_2_forward
GCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCT
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@SEQ_3_forward
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@SEQ_4_forward
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@SEQ_5_forward
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
EOF

    # Reverse reads (_2)
    cat > "test_data/${sample}_2.fq" << 'EOF'
@SEQ_1_reverse
CGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGAT
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@SEQ_2_reverse
AGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGC
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@SEQ_3_reverse
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@SEQ_4_reverse
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@SEQ_5_reverse
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
EOF

    # Compress the files
    gzip "test_data/${sample}_1.fq"
    gzip "test_data/${sample}_2.fq"
done

echo "✅ Created test FASTQ files:"
ls -la test_data/
echo
echo "📁 Test files are in: ./test_data/"
echo "   Use these for testing file upload and pipeline stages."
echo
echo "🧪 To test the pipeline:"
echo "1. Start ExpressDiff: ./launch_expressdiff.sh"
echo "2. Create a new run"
echo "3. Upload the test files from test_data/"
echo "4. Run the pipeline stages"